version: '3.8'

services:
  main-database:
    image: postgres
    container_name: rth-main-database
    environment:
      POSTGRES_DB: 'rate_the_hero'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '12345678'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
